version: "3.9"

services:
  backend:
    build: ./backend
    command: [ "/bin/sh", "/backend/docker/app.sh" ]
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - ./backend/.env
    ports:
      - "8085:4000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    command: -p 1221
    expose:
      - 1221
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    depends_on:
      - db

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.10.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  postgres_data:
