version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev
    volumes:
      - db_data:/var/lib/postgresql/data


  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db_data:
