"""add News table

Revision ID: 8fa8c731a187
Revises: 
Create Date: 2023-12-27 21:55:30.295184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa8c731a187'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('href', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('country', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('city', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('topical_keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news')),
    sa.UniqueConstraint('title_en', name=op.f('uq_news_title_en'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
