"""new column NEWS

Revision ID: 702cabc1c713
Revises: 798315e310bc
Create Date: 2023-10-20 09:20:52.412037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702cabc1c713'
down_revision = '798315e310bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title_en', sa.String(), nullable=True))
    op.add_column('news', sa.Column('title_ru', sa.String(), nullable=True))
    op.add_column('news', sa.Column('image_text_en', sa.String(), nullable=True))
    op.add_column('news', sa.Column('image_text_ru', sa.String(), nullable=True))
    op.drop_constraint('news_title_key', 'news', type_='unique')
    op.create_unique_constraint(None, 'news', ['title_en'])
    op.create_unique_constraint(None, 'news', ['title_ru'])
    op.drop_column('news', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_constraint(None, 'news', type_='unique')
    op.create_unique_constraint('news_title_key', 'news', ['title'])
    op.drop_column('news', 'image_text_ru')
    op.drop_column('news', 'image_text_en')
    op.drop_column('news', 'title_ru')
    op.drop_column('news', 'title_en')
    # ### end Alembic commands ###
