"""update table news

Revision ID: ffcc4b9c0ec2
Revises: 
Create Date: 2023-11-18 12:11:38.961021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffcc4b9c0ec2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=True),
    sa.Column('title_ru', sa.String(), nullable=True),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('country', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('city', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('topical_keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_en'),
    sa.UniqueConstraint('title_ru')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
