"""new models

Revision ID: 798315e310bc
Revises: 
Create Date: 2023-10-18 09:48:59.338607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '798315e310bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('country')
    op.add_column('news', sa.Column('image', sa.String(), nullable=True))
    op.add_column('news', sa.Column('country', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('news', sa.Column('city', sa.ARRAY(sa.String()), nullable=True))
    op.create_unique_constraint(None, 'news', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news', type_='unique')
    op.drop_column('news', 'city')
    op.drop_column('news', 'country')
    op.drop_column('news', 'image')
    op.create_table('country',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='country_pkey')
    )
    # ### end Alembic commands ###
